spring.application.name=bidding-service
server.port=8082
auction-service.url=http://localhost:8080
spring.datasource.url=jdbc:postgresql://localhost:5432/auctiondb
spring.datasource.username=auctionuser
spring.datasource.password=auctionpass
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.table=flyway_bidding_schema_history
spring.kafka.bootstrap-servers=[::1]:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
logging.level.com.example.biddingservice=INFO
logging.level.org.springframework.kafka=DEBUG
